routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SA\CategoryController;
use App\Http\Controllers\User\WordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

//SA
Route::middleware('sa')->name('sa.')->prefix('sa')->group(function() {
    //CATEGORY
    Route::get('/category', [CategoryController::class, 'index'])->name('category.index');
    Route::get('/category/create', [CategoryController::class, 'create'])->name('category.create');
    Route::post('/category/create', [CategoryController::class, 'store']);
    Route::get('/category/edit/{category:slug}', [CategoryController::class, 'edit'])->name('category.edit');
    Route::post('/category/edit/{category:slug}', [CategoryController::class, 'update']);
    Route::get('/category/delete/{category:slug}', [CategoryController::class, 'delete'])->name('category.delete');
});

//USER
Route::middleware(['auth:sanctum', 'verified'])->name('user.')->prefix('user')->group(function() {
   //WORDS
    Route::get('/word', [WordController::class, 'index'])->name('word.index');
    Route::get('/word/create', [WordController::class, 'create'])->name('word.create');
    Route::post('/word/create', [WordController::class, 'store']);
    Route::get('/word/edit/{word:id}', [WordController::class, 'edit'])->name('word.edit');
    Route::post('/word/edit/{word:id}', [WordController::class, 'update']);
    Route::get('/word/delete/{word:id}', [WordController::class, 'delete'])->name('word.delete');
   //PENDINGS
    Route::get('/word/pending/delete/{pending:id}', [WordController::class, 'deletePending'])->name('word.delete.pending');
    Route::get('/word/pending/show/{pending:id}', [WordController::class, 'showPending'])->name('word.show.pending');
    Route::post('/word/accept/{pending:id}', [WordController::class, 'acceptPending'])->name('word.accept.pending');
});

app/Models/Pending.php
<?php

namespace App\Models;

use App\Actions\Pending\Captcha;
use App\Actions\Pending\PendingValidation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\Models\Word;

class Pending extends Model {
    use HasFactory;

    protected $guarded = ['id'];

    public function new(Request $request): bool {
        if (PendingValidation::isValid($request) && Captcha::check($request->recaptcha)) {
            self::create($request->all());
            return true;
        } else {
            return false;
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
        'sa'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/User/WordController.php
<?php

namespace App\Http\Controllers\User;

use App\Actions\Word\GetWord;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Pending;
use App\Models\Word;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class WordController extends Controller {

    public function __construct(Word $word) {
        $this->word = $word;
    }

    public function index(): View {
        $words = GetWord::paginate('created_at', 'DESC', 15);
        return view('user/word/index', [
            'words' => $words
        ]);
    }

    public function create(): View {
        $categories = Category::all();
        return view('user/word/create', [
            'categories' => $categories
        ]);
    }

    public function store(Request $request): RedirectResponse {
        if ($this->word->new($request)) {
            return redirect()->route('user.word.index')->with('success', 'Word successfully created.');
        } else {
            return back()->with('error', 'Word creation failed.');
        }
    }

    public function edit(Word $word): View {
        $categories = Category::all();
        return view('user/word/edit', [
           'word' => $word,
           'categories' => $categories
        ]);
    }

    public function update(Word $word, Request $request): RedirectResponse {
        if ($this->word->change($word, $request)) {
            return redirect()->route('user.word.index')->with('success', 'Word successfully edited.');
        } else {
            return back()->with('error', 'Edit failed.');
        }
    }

    public function delete(Word $word): RedirectResponse {
        try {
            $word->delete();
        } catch (\Exception $e) {
            echo $e;
        }

        return redirect()->route('user.word.index')->with('success', 'Word successfully deleted.');
    }

    public function acceptPending(Request $request, Pending $pending): RedirectResponse {
        if ($this->word->accept($request, $pending)) {
            return redirect()->route('dashboard')->with('success', 'Pending word accepted successfully!');
        } else {
            return back()->with('error', "Pending word wasn't accepted unfortunately.");
        }
    }

    public function deletePending(Pending $pending): RedirectResponse {
        try {
            $pending->delete();
        } catch (\Exception $e) {
            echo $e;
        }

        return back()->with('success', 'Pending successfully deleted.');
    }

    public function showPending(Pending $pending): View {
        $categories = Category::all();
        return view('/user/pending/show', compact('pending', 'categories'));
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/pending/show.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ $pending->hanzi }}
    </x-slot>

        <div class="max-w-7xl mx-auto text-left p-3 px-8 text-white">
            <table class="table-auto w-1/2 text-xl">
                <form action="{{ route('user.word.accept.pending', $pending->id) }}" method="POST">
                    @csrf
                    <tr>
                        <th>Hanzi</th>
                        <td class="p-3">
                            <a href="https://translate.google.com/?sl=zh-CN&tl=en&text={{ $pending->hanzi }}&op=translate" class="transition duration-300 text-purple hover:text-green" target="_blank" rel="noopener norefresh">
                                {{ $pending->hanzi }}
                            </a>
                        </td>
                    </tr>

                    <tr>
                        <th>Pinyin</th>
                        <td class="p-3">{{ $pending->pinyin }}</td>
                    </tr>

                    <tr>
                        <th>Translation</th>
                        <td class="p-3">{{ $pending->translation }}</td>
                    </tr>

                    <tr>
                        <th>Level</th>
                        <td class="p-3">
                            <select name="level" class="bg-transparent p-2 border w-3/4">
                                <option value="beginner">Beginner</option>
                                <option value="intermediate">Intermediate</option>
                                <option value="advanced">Advanced</option>
                            </select>
                        </td>
                    </tr>

                    <tr>
                        <th>Category</th>
                        <td class="p-3">
                            <select name="category" class="bg-transparent p-2 border w-3/4">
                                @foreach ($categories as $c)
                                    <option value="{{ $c->id }}">{{ $c->name }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>

                    <tr>
                        <th></th>
                        <td class="p-3 pt-12">
                            <button type="submit" class="transition duration-300 hover:bg-gray-700 p-3 bg-transparent border">Save</button>
                        </td>
                    </tr>
                </form>
            </table>
        </div>
</x-app-layout>