routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SA\CategoryController;
use App\Http\Controllers\User\WordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

//SA
Route::middleware('sa')->name('sa.')->prefix('sa')->group(function() {
    //CATEGORY
    Route::get('/category', [CategoryController::class, 'index'])->name('category.index');
    Route::get('/category/create', [CategoryController::class, 'create'])->name('category.create');
    Route::post('/category/create', [CategoryController::class, 'store']);
    Route::get('/category/edit/{category:slug}', [CategoryController::class, 'edit'])->name('category.edit');
    Route::post('/category/edit/{category:slug}', [CategoryController::class, 'update']);
    Route::get('/category/delete/{category:slug}', [CategoryController::class, 'delete'])->name('category.delete');
});

//USER
Route::middleware(['auth:sanctum', 'verified'])->name('user.')->prefix('user')->group(function() {
   //WORDS
    Route::get('/word', [WordController::class, 'index'])->name('word.index');
    Route::get('/word/create', [WordController::class, 'create'])->name('word.create');
    Route::post('/word/create', [WordController::class, 'store']);
    Route::get('/word/edit/{word:id}', [WordController::class, 'edit'])->name('word.edit');
    Route::post('/word/edit/{word:id}', [WordController::class, 'update']);
    Route::get('/word/delete/{word:id}', [WordController::class, 'delete'])->name('word.delete');
   //PENDINGS
    Route::get('/word/pending/delete/{pending:id}', [WordController::class, 'deletePending'])->name('word.delete.pending');
    Route::get('/word/pending/show/{pending:id}', [WordController::class, 'showPending'])->name('word.show.pending');
    Route::post('/word/accept/{pending:id}', [WordController::class, 'acceptPending'])->name('word.accept.pending');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
        'sa'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Models/Word.php
<?php

namespace App\Models;

use App\Actions\Word\GetWord;
use App\Actions\Word\WordValidation;
use Illuminate\Support\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Pending;

/**
 * @method static create()
 * @method static where(string $string, string $level)
 */

class Word extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function categories() {
        return $this->belongsTo(Category::class, 'category');
    }

    public function new(Request $request): bool {
        if (WordValidation::isValid($request)) {
            self::create($request->all());
            return true;
        } else {
            return false;
        }
    }

    public function change(Word $word, Request $request): bool {
        if (WordValidation::isValid($request)) {
            $word->update($request->all());
            $word->save();
            return true;
        } else {
            return false;
        }
    }

    public function random(): Collection {
        $words = self::all();
        return $words->random(1);
    }

    public function learnNew(string $level): Collection {
        return DB::table('words')
            ->where('level', $level)
            ->inRandomOrder()
            ->limit(10)
            ->get();
    }

    public function train(string $level): array {
        return GetWord::mixTranslations($level);
    }

    public function accept(Request $request, Pending $pending): bool {
        $mergedData = array_merge($request->all(), $pending->attributesToArray());

        if($mergedData != null) {
            self::create($mergedData);
            $pending->delete();
            return true;
        } else {
            return false;
        }
    }
}

app/Http/Controllers/User/WordController.php
<?php

namespace App\Http\Controllers\User;

use App\Actions\Word\GetWord;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Pending;
use App\Models\Word;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class WordController extends Controller {

    public function __construct(Word $word) {
        $this->word = $word;
    }

    public function index(): View {
        $words = GetWord::paginate('created_at', 'DESC', 15);
        return view('user/word/index', [
            'words' => $words
        ]);
    }

    public function create(): View {
        $categories = Category::all();
        return view('user/word/create', [
            'categories' => $categories
        ]);
    }

    public function store(Request $request): RedirectResponse {
        if ($this->word->new($request)) {
            return redirect()->route('user.word.index')->with('success', 'Word successfully created.');
        } else {
            return back()->with('error', 'Word creation failed.');
        }
    }

    public function edit(Word $word): View {
        $categories = Category::all();
        return view('user/word/edit', [
           'word' => $word,
           'categories' => $categories
        ]);
    }

    public function update(Word $word, Request $request): RedirectResponse {
        if ($this->word->change($word, $request)) {
            return redirect()->route('user.word.index')->with('success', 'Word successfully edited.');
        } else {
            return back()->with('error', 'Edit failed.');
        }
    }

    public function delete(Word $word): RedirectResponse {
        try {
            $word->delete();
        } catch (\Exception $e) {
            echo $e;
        }

        return redirect()->route('user.word.index')->with('success', 'Word successfully deleted.');
    }

    public function acceptPending(Request $request, Pending $pending): RedirectResponse {
        if ($this->word->accept($request, $pending)) {
            return redirect()->route('dashboard')->with('success', 'Pending word accepted successfully!');
        } else {
            return back()->with('error', "Pending word wasn't accepted unfortunately.");
        }
    }

    public function deletePending(Pending $pending): RedirectResponse {
        try {
            $pending->delete();
        } catch (\Exception $e) {
            echo $e;
        }

        return back()->with('success', 'Pending successfully deleted.');
    }

    public function showPending(Pending $pending): View {
        $categories = Category::all();
        return view('/user/pending/show', compact('pending', 'categories'));
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/word/create.blade.php
<x-app-layout>

    <x-slot name="header">
        Create Word
    </x-slot>

    <x-slot name="slot">
        <div class="max-w-7xl mx-auto px-4 py-12 text-white text-lg grid grid-rows-3">
            <form method="POST">
                @csrf

                <div class="px-6">
                    <label>
                        <p class="pb-4">Category</p>
                        <select name="category" class="bg-transparent p-2 border w-1/3">
                            @foreach ($categories as $c)
                                <option value="{{ $c->id }}">{{ $c->name }}</option>
                            @endforeach
                        </select>
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Hanzi</p>
                        <input type="text" name="hanzi" id="hanzi" class="bg-transparent p-2 border w-1/3">
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Pinyin</p>
                        <input type="text" name="pinyin" id="pinyin" class="bg-transparent p-2 border w-1/3">
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Translation</p>
                        <input type="text" name="translation" id="translation" class="bg-transparent p-2 border w-1/3">
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Level</p>
                        <select name="level" class="bg-transparent p-2 border w-1/3">
                            <option value="beginner">Beginner</option>
                            <option value="intermediate">Intermediate</option>
                            <option value="advanced">Advanced</option>
                        </select>
                    </label>
                </div>

                <div class="px-6 pt-8">
                    <button type="submit" class="transition duration-300 border hover:bg-gray-700 p-3">Create</button>
                </div>

            </form>
        </div>
    </x-slot>

</x-app-layout>

resources/views/user/word/edit.blade.php
<x-app-layout>

    <x-slot name="header">
        Edit Word
    </x-slot>

    <x-slot name="slot">
        <div class="max-w-7xl mx-auto px-4 py-12 text-white text-lg grid grid-rows-3">
            <form method="POST">
                @csrf

                <div class="px-6">
                    <label>
                        <p class="pb-4">Category</p>
                        <select name="category" class="bg-transparent p-2 border w-1/3">
                            @foreach ($categories as $c)
                                <option value="{{ $c->id }}" @if ($c->id === $word->category) selected @endif>{{ $c->name }}</option>
                            @endforeach
                        </select>
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Hanzi</p>
                        <input type="text" name="hanzi" id="hanzi" value="{{ $word->hanzi }}" class="bg-transparent p-2 border w-1/3">
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Pinyin</p>
                        <input type="text" name="pinyin" id="pinyin" value="{{ $word->pinyin }}" class="bg-transparent p-2 border w-1/3">
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Translation</p>
                        <input type="text" name="translation" id="translation" value="{{ $word->translation }}" class="bg-transparent p-2 border w-1/3">
                    </label>
                </div>

                <div class="px-6 pt-4">
                    <label>
                        <p class="pb-4">Level</p>
                        <select name="level" class="bg-transparent p-2 border w-1/3">
                            <option value="beginner" @if ($word->level === "beginner") selected @endif>Beginner</option>
                            <option value="intermediate" @if ($word->level === "intermediate") selected @endif>Intermediate</option>
                            <option value="advanced" @if ($word->level === "advanced") selected @endif>Advanced</option>
                        </select>
                    </label>
                </div>

                <div class="px-6 pt-8">
                    <button type="submit" class="transition duration-300 border hover:bg-gray-700 p-3">Edit</button>
                </div>

            </form>
        </div>
    </x-slot>

</x-app-layout>

resources/views/user/word/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="grid grid-cols-2">
            <div>
                Words
                @if (session('success'))
                    | {{ session('success') }}
                @endif
            </div>

            <div class="text-right">
                <a href="{{ route('user.word.create') }}" class="transition duration-300 text-lg p-3 border hover:bg-gray-700">Create</a>
            </div>

    </x-slot>

    <x-slot name="slot">
        <div class="max-w-7xl mx-auto py-12 px-4 text-white">
            <div class="pt-6 px-4">
                <table class="table-auto w-full">
                    <tr class="text-left">
                        <th>Hanzi</th>
                        <th>Pinyin</th>
                        <th>Translation</th>
                        <th>Level</th>
                        <th>Category</th>
                        <th class="text-right">Actions</th>
                    </tr>

                    @foreach ($words as $w)
                        <tr>
                            <td>{{ $w->hanzi }}</td>
                            <td>{{ $w->pinyin }}</td>
                            <td>{{ $w->translation }}</td>
                            <td>{{ $w->level }}</td>
                            <td>{{ App\Models\Category::where('id', $w->category)->first()->name }}</td>
                            <td class="text-right">
                                <a href="{{ route('user.word.edit', $w->id) }}" class="transition duration-300 text-yellow hover:green">Edit</a>
                                <a href="{{ route('user.word.delete', $w->id) }}" class="transition duration-300 text-red hover:text-purple" onclick="return confirm('Do you really want to remove this word?')">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </table>

                <div class="bg-transparent pt-12">
                    {{ $words->links() }}
                </div>
            </div>
        </div>
    </x-slot>
</x-app-layout>