routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SA\CategoryController;
use App\Http\Controllers\User\WordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

//SA
Route::middleware('sa')->name('sa.')->prefix('sa')->group(function() {
    //CATEGORY
    Route::get('/category', [CategoryController::class, 'index'])->name('category.index');
    Route::get('/category/create', [CategoryController::class, 'create'])->name('category.create');
    Route::post('/category/create', [CategoryController::class, 'store']);
    Route::get('/category/edit/{category:slug}', [CategoryController::class, 'edit'])->name('category.edit');
    Route::post('/category/edit/{category:slug}', [CategoryController::class, 'update']);
    Route::get('/category/delete/{category:slug}', [CategoryController::class, 'delete'])->name('category.delete');
});

//USER
Route::middleware(['auth:sanctum', 'verified'])->name('user.')->prefix('user')->group(function() {
   //WORDS
    Route::get('/word', [WordController::class, 'index'])->name('word.index');
    Route::get('/word/create', [WordController::class, 'create'])->name('word.create');
    Route::post('/word/create', [WordController::class, 'store']);
    Route::get('/word/edit/{word:id}', [WordController::class, 'edit'])->name('word.edit');
    Route::post('/word/edit/{word:id}', [WordController::class, 'update']);
    Route::get('/word/delete/{word:id}', [WordController::class, 'delete'])->name('word.delete');
   //PENDINGS
    Route::get('/word/pending/delete/{pending:id}', [WordController::class, 'deletePending'])->name('word.delete.pending');
    Route::get('/word/pending/show/{pending:id}', [WordController::class, 'showPending'])->name('word.show.pending');
    Route::post('/word/accept/{pending:id}', [WordController::class, 'acceptPending'])->name('word.accept.pending');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\Actions\Category\CategoryValidation;
use App\Actions\Slugify;

/**
 * @method static create(array $all)
 */

class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function words() {
        return $this->hasMany(Word::class);
    }

    public function new(Request $request): bool {
        $slug = Slugify::new($request->name);
        if (CategoryValidation::isValid($request)) {
            $merged = array_merge($request->all(), ['slug' => $slug]);
            Category::create($merged);
            return true;
        } else {
            return false;
        }
    }

    public function change(Category $category, Request $request): bool {
        $slug = Slugify::new($request->name);
        if (CategoryValidation::isValidEdit($request)) {
            $merged = array_merge($request->all(), ['slug' => $slug]);
            $category->update($merged);
            $category->save();

            return true;
        } else {
            return false;
        }
    }
}

app/Http/Controllers/SA/CategoryController.php
<?php

namespace App\Http\Controllers\SA;

use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;
use App\Models\Category;

class CategoryController extends Controller {

    private $category;

    public function __construct(Category $category) {
        $this->category = $category;
    }

    public function index(): View {
        $categories = DB::table('categories')->orderByDesc('created_at')->get();
        return view('sa/category/index', compact('categories'));
    }

    public function create(): View {
        return view('sa/category/create');
    }

    public function store(Request $request): RedirectResponse {
        if ($this->category->new($request)) {
            return redirect()->route('sa.category.index')->with('success', 'Category was created successfully.');
        } else {
            return back()->with('error', 'Category creation failed.');
        }
    }

    public function edit(Category $category): View {
        return view('sa/category/edit', [
           'category' => $category
        ]);
    }

    public function update(Category $category, Request $request): RedirectResponse {
        if ($this->category->change($category, $request)) {
            return redirect()->route('sa.category.index')->with('success', 'Category was edited successfully.');
        } else {
            return back()->with('error', 'Category edit failed.');
        }
    }

    public function delete(Category $category): RedirectResponse {
        try {
            $category->delete();
        } catch (\Exception $e) {
            echo $e;
        }

        return redirect()->route('sa.category.index')->with('success', 'Category was successfully deleted.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/sa/category/create.blade.php
<x-app-layout>
    <x-slot name="header">
        Create Category
        @if (session('error'))
            | {{ session('error') }}
        @endif
    </x-slot>

    <x-slot name="slot">
        <div class="max-w-7xl mx-auto px-4 py-12 text-white text-lg grid grid-rows-3">
            <form method="POST">
                @csrf

                <div class="px-6">
                    <label>
                        <p class="pb-4">Name</p>
                        <input type="text" name="name" id="name" class="@error('name') bg-red-200 @enderror bg-transparent border p-2 w-1/2" value="{{ old('name') }}">
                        @error('name') Name already in use. @enderror
                    </label>

                </div>

                <div class="pt-6 px-6">
                    <label>
                        <p class="pb-6">Description</p>
                        <textarea name="description" id="description" class="bg-transparent w-1/2 border p-2">{{ old('description') }}</textarea>
                        @error('description') Description too short @enderror
                    </label>

                </div>

                <div class="pt-6 px-6">
                    <button type="submit" class="transition duration-300 border hover:bg-gray-700 p-3">Create</button>
                </div>
            </form>
        </div>
    </x-slot>

</x-app-layout>

resources/views/sa/category/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        Edit Category
    </x-slot>

    <x-slot name="slot">
        <div class="max-w-7xl mx-auto px-4 py-12 text-white text-lg grid grid-rows-3">
            <form method="POST">
                @csrf

                <div class="px-6">
                    <label>
                        <p class="pb-4">Name</p>
                        <input type="text" name="name" id="name" class="@error('name') bg-red-200 @enderror bg-transparent border p-2 w-1/2" value="{{ $category->name }}">
                        @error('name') Name already in use. @enderror
                    </label>

                </div>

                <div class="pt-6 px-6">
                    <label>
                        <p class="pb-6">Description</p>
                        <textarea name="description" id="description" class="bg-transparent w-1/2 border p-2">{{ $category->description }}</textarea>
                        @error('description') Description too short @enderror
                    </label>

                </div>

                <div class="pt-6 px-6">
                    <button type="submit" class="transition duration-300 border hover:bg-gray-700 p-3">Edit</button>
                </div>
            </form>
        </div>
    </x-slot>

</x-app-layout>

resources/views/sa/category/index.blade.php
<x-app-layout>

    <x-slot name="header">
        <div class="grid grid-cols-2">
            <div>Categories
                @if (session('success'))
                    | {{ session('success') }}
                @endif</div>
            <div class="text-right">
                <a href="{{ route('sa.category.create') }}" class="transition duration-300 text-lg p-3 border hover:bg-gray-700">Create</a>
            </div>
        </div>

    </x-slot>

    <x-slot name="slot">
        <div class="max-w-7xl mx-auto py-12 px-4 text-white">
            <div class="pt-6 px-4">
                <table class="table-auto w-full">
                    <tr class="text-left">
                        <th>ID</th>
                        <th>Date</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th class="text-right">Actions</th>
                    </tr>

                    @foreach ($categories as $c)
                        <tr>
                            <td>{{ $c->id }}</td>
                            <td>{{ $c->created_at }}</td>
                            <td>{{ $c->name }}</td>
                            <td>{{ $c->description }}</td>
                            <td class="text-right">
                                <a href="{{ route('sa.category.edit', $c->slug) }}" class="transition duration-300 text-yellow hover:green">Edit</a>
                                <a href="{{ route('sa.category.delete', $c->slug) }}" class="transition duration-300 text-red hover:text-purple">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </x-slot>
</x-app-layout>